- name: Lock user screen
  hosts: all
  vars:
         ansible_python_interpreter: /usr/bin/python3
  gather_facts: no
  become: true
  become_method: sudo
  ignore_errors: true
  tasks:
          - name: Lock PC
            systemd:
                 name: i3lock
                 state: started  
            tags:
            
                  - lock
                          
- name: Unlock user screen
  hosts: all
  vars:
         ansible_python_interpreter: /usr/bin/python3
  gather_facts: no
  become: true
  become_method: sudo
  ignore_errors: true
  tasks:
          - name: Unlock PC  
            systemd: 
                  name: i3lock
                  state: stopped
            tags:
                  - unlock




- name: Start a browser
  hosts: all
  vars:
         ansible_python_interpreter: /usr/bin/python3
  gather_facts: no
  become: true
  become_method: sudo
  ignore_errors: true
  tasks:  
          - name: Go to browser       
            script: open_browser.sh
            tags:
                  - browser
